site_name: ""
site_url: https://marslearnings.github.io/marslearnings/
theme:
  name: material
  font:
    text: Roboto
    code: Red Hat Mono
  logo: assets/white_logo_crop.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs.sticky
    - navigation.sections

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      accent: cyan
    
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      accent: cyan

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search
  - blog:
      archive_date_format: MMMM yyyy
      categories_allowed:
        - Python
        - News
  # - tags:
  #   - tags_file: blog/tags.md

nav:
  - Home:
    - index.md
    - code-examples.md
    - admonitions.md
    - diagrams-examples.md
  - Blog:
    - blog/index.md
    # - Tags: blog/tags.md

extra:
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@datascienceanywhere

copyright: copyright &copy; 2025 MARS Learnings